### ISSUE TITLE
[FEATURE] Multiple day tournaments

### ISSUE THREAD

**Issue by madarasz** [madarasz/always-be-running#14]
**User story**: As a TO, I want to create tournaments that span for multiple days.

**More details**: Especially useful for online tournaments
**Development effort**: medium

**Things to consider**
- DB needs an end date field.
- Integration with current calendar could be problematic. How about we only show the start date in the calendar?

**Comment by GuvBubbs** [comment]
2 day events are in the system

https://www.facebook.com/events/409587469430544/
http://www.alwaysberunning.net/tournaments/101

Just an FYI

**Comment by GuvBubbs** [comment]
Will become more important when Regionals are announced

**Comment by GuvBubbs** [comment]
Speaking of regionals...

**Comment by madarasz** [comment]
Still something that you can announce in the description field easily, I don't see much added value.
