### ISSUE TITLE
[FEATURE] Non-tournament, casual event type

### ISSUE THREAD

**Issue by madarasz** [madarasz/always-be-running#15]
**User story**: As a TO, I want to create a Netrunner event which is not a tournament, but a casual meeting

**More details**: New tournament type should be created. Conclusion and claiming should be disabled.
**Development effort**: low

**Things to consider**

**Comment by GuvBubbs** [comment]
Cool to have this in but without it reoccurring it doesn't seem as useful.

https://github.com/madarasz/always-be-running/issues/16

**Comment by GuvBubbs** [comment]
Hey I just saw that you added reoccurring events. That's awsome!

I on that point it might be good if you added an option to "Legal cardpool up to" Like NA/Other.

Not just for weekly hangouts but also for special events.
http://puu.sh/saeqb/0ecaeeb8d2.png
