### ISSUE TITLE
[FEATURE] Reoccurring "tournaments"

### ISSUE THREAD

**Issue by madarasz** [madarasz/always-be-running#16]
**User story**: As a TO, I want to create an event that is reoccurring. This is very useful for casual Netrunner meetups.

**More details**:
**Development effort**: low / medium

**Things to consider**
- Setting the time period of the reoccurrence can be complicated. Implementing weekly reoccurrence is easy. Implementing last Saturday of every month is hell.
- How to store this in DB?
- Should it be displayed in the "Upcoming" section? Calendars should contain it.
- How should you handle registering for the event? Should the list of registered users be cleared after each event? Will the users update it each time themselves?

**Comment by GuvBubbs** [comment]
Hey I just saw that you added reoccurring events. That's awsome!

I on that point it might be good if you added an option to "Legal cardpool up to" Like NA/Other.

Not just for weekly hangouts but also for special events.
http://puu.sh/saeqb/0ecaeeb8d2.png

**Comment by madarasz** [comment]
Recurring events have no legal cardpool field from now on. There's an overlay blocking the field in the tournament form, also it is not displayed on the tournament page.
