### ISSUE TITLE
Being able to set username

### ISSUE THREAD

**Issue by GuvBubbs** [madarasz/always-be-running#17]
Users would like to be able to set usernames.
![image](https://cloud.githubusercontent.com/assets/22435318/19986820/07ce7958-a27d-11e6-83e6-274eb6830371.png)

Maybe login with NRDB for auth but pick a username in settings

**Comment by madarasz** [comment]
Noted, will add when I develop the user profile part.

**Comment by madarasz** [comment]
Done, you can set displayed name in your profile.

**Comment by GuvBubbs** [comment]
Awesome. What is the name field for?
http://puu.sh/sb9v2/13251944c1.png

Should it be real name?
