### ISSUE TITLE
No www not working

### ISSUE THREAD

**Issue by GuvBubbs** [madarasz/always-be-running#18]
Could you make http://alwaysberunning.net/ redirect to http://**_www_**.alwaysberunning.net/

**Comment by Smashman** [comment]
Yes this is a fairly major issue.

**Comment by gereons** [comment]
Agreed, www and non-www should behave the same, but I would suggest making the non-www domain the default, and also use https exclusively.

**Comment by madarasz** [comment]
HTTPS is not a problem. As for non-www (apex/naked) domain: I am not an expert in this area, but it seems to me that the option depends on the hosting company you are at. There are free services for this kind of non-www redirection as a third party, but there is a huge security hole there which I am unwilling to take.

**Comment by Smashman** [comment]
It's definitely not related to the hosting company. Who currently hosts the site?

**Comment by madarasz** [comment]
Ow, my bad. A DNS record of mine was off, fixed it, it was so easy. Now it should work from http://alwaysberunning.net . I will fix add the https redirect later on.

**Comment by Smashman** [comment]
Great

**Comment by madarasz** [comment]
From now on HTTPS is enforced on AlwaysBeRunning.
