### ISSUE TITLE
Wrong link for corporation deck in "Your claim" on a Tournament page

### ISSUE THREAD

**Issue by Saintis** [madarasz/always-be-running#22]
<img width="296" alt="screen shot 2016-11-21 at 14 57 20" src="https://cloud.githubusercontent.com/assets/13198563/20487359/ead55278-affa-11e6-9710-bcb89658b9fb.png">

The underline link above "Fiery Info" links to https://netcorpdb.com/en/deck/view/808555 when it should link to https://netrunnerdb.com/en/deck/view/808555.

Looks like a `runner` -> `corp` replace gone wrong.

**Comment by Saintis** [comment]
Had a look. Seems error is here: https://github.com/madarasz/always-be-running/blob/master/resources/views/tournaments/view.blade.php#L234

**Comment by madarasz** [comment]
Good catch, fixed.
Note to self: do not use find and replace feature when copy-pasting 'runner' and 'corp' parts :D
