### ISSUE TITLE
[BUG] Cannot manually add player without giving top cut placing.

### ISSUE THREAD

**Issue by lpoulter** [madarasz/always-be-running#24]
I want to manually add a player who came 9th in a 16 player event that had a top 8 cut.

I need to remove the option to add to top cut if swiss place > topcut size.

![image](https://cloud.githubusercontent.com/assets/3940567/20865596/a4816eb0-ba0e-11e6-86cf-19c57766a69c.png)

**Comment by madarasz** [comment]
Woops, forgot about that. Added "n/a" to top-cut values.
