### ISSUE TITLE
[Feature Request] Allow claiming spots without having to provide a decklist.

### ISSUE THREAD

**Issue by gereons** [madarasz/always-be-running#25]
Alternatively, allow people get rid of the "claim your spot" notification without claiming.

**Comment by madarasz** [comment]
It's the basic philosophy of the site that you claim with your decklists. No decklist, no glory :)

As for getting rid of the notification, you can unregister from the tournament. Maybe I will put that button on the Personal page as well.

**Comment by madarasz** [comment]
'unregister' link added to the table on Personal page. (When a tournament has opened for claiming which the user registered to)
