### ISSUE TITLE
[FEATURE] Make the creation of events quicker

### ISSUE THREAD

**Issue by lpoulter** [madarasz/always-be-running#29]
I'm trying to make ABR the single point of reference for events in the UK improve the speed of event input would help. Currently a spreadsheet is also being used. 

Some ideas:

- Do all the mandatory fields really need to be mandatory, location for instance?  
- A bulk add would be useful perhaps from CSV.
- A chrome plugin to create from FB event into ABR

**Comment by madarasz** [comment]
Hmmm... interesting idea. My goal is to have the actual TOs active on the site. You are a great help, you alone have added a largest number of tournaments which is great. But in the long run, it would be better if TOs add the tournaments and their results, minimizing your workload on being the admin of the UK. If TOs do stuff themselves, I don't think mass input is necessary. 

I would really want to keep the location (country and city are mandatory), so the map works. Think of it if there were a user story: "As a foreigner, I want to find and participate in Netrunner events in my area."

Minimizing input is a good principle. I think I will remove "tournament title" from the mandatory field list. If left empty it can be constructed from "store/city name" + "tournament type". In 90% of cases, this is the title users give anyways.

**Comment by lpoulter** [comment]
Yeah i agree with the aim to have all TO's input data. I do think that will take time however and it will never reach 100%. Good idea with the title. I've been using `location` - `store` - `type` already.

**Comment by lpoulter** [comment]
Yeah i can see your point about the location.

**Comment by madarasz** [comment]
`Tournament title` field is no longer mandatory.

If left empty, it will be constructed as `store name` - `type`. If store name is not provided, then `location city` - `type`. I try to skip `location city` because tournament tables already have it.
