### ISSUE TITLE
[FEATURE] Personal settings - default country filter

### ISSUE THREAD

**Issue by madarasz** [madarasz/always-be-running#3]
**User story**: As a ABR user, I want a personal setting for the default country filtering for upcoming tournaments. Most of the time I am only interested in the country I am living in. This features saves me time.

**More details**: This should be a setting in the personal page. The user can still filter to any country he/she wants to.
**Development effort**: low

**Things to consider**
- online tournaments should be shown regardless of country filtering
- What to do when there is no upcoming tournament for the default country filter? Should we just set the country filter to "---" (not filtering) or display a message that the country has no upcoming tournaments? Or both?

**Comment by GuvBubbs** [comment]
A thought on this. 

Once it's in maybe you could show all events for that country on the personal page.

**Comment by GuvBubbs** [comment]
Default country does not apply to upcoming weekly events unless you play with the dropdown.

http://puu.sh/swPKw/d986edf1d8.png

**Comment by madarasz** [comment]
Should be fixed.
