### ISSUE TITLE
[FEATURE] Create "Leagues", rankings from the tournament results.

### ISSUE THREAD

**Issue by lpoulter** [madarasz/always-be-running#30]
These would be similar to acoo or my ranking system, here https://docs.google.com/spreadsheets/d/1eJER2eYX4rhIEs1QqUFvLjr08L2Hx6qN9R0mZeqoe6M/edit?usp=sharing

**Comment by madarasz** [comment]
Ok, Let's cook up some specifications which are somewhat general. I want to have rules which are suitable for a wide range of TOs and avoid everybody wanting their highly custom ruleset.

Let's say you can create a "League" which consists of tournaments. You can add or remove these tournaments from the League. (I don't want to auto-add tournaments based on location or date, I think it's better if the organizer has full control and knowledge of the tournaments.) 

Out of these tournaments, you get points. You can either get all the points from all your tournaments, or you can get points from your best N number of tournaments overall. (I saw you are taking this further by counting the best 3 store championships and best 2 regionals - it's quite hard to pin down rules like that.)

How do you calculate the points for a tournament? Does the number of participants count? Do you consider the actual tournament points (FFG rules) made during the tournament?

How do we track all the players of all the tournaments? Can you make sure that the results are always recorded? If a player claims on ABR all the time, that's easy. What if a player does not claim at all? How do we make sure that he/she is on the tournaments with the same imported name? What if a player sometimes claim sometimes don't? How do we match the user with the imported names?

**Comment by lpoulter** [comment]
Lots of good questions.
I'll start with how my system works.
- I manually collect results and associate with players. 
- Points are calculated based on both level of competition - SC/Regional and players.
- Players only get points for making the cut or above.

I like your idea of a league where by a TO selects the events that count. 

As you saying associating with players is the hardest part. I think to work best it would require players to claim their results to be eligible for points. I think this would work quite well as the same players who claim their results are likely the one's who care about rankings. 

Perhaps some kind of auto association would help. This could be based on name given to the TO. The ability for the rankings organiser to manually associate results or remove association would likely be needed as well.

I've had people from both USA and the Nordics ask me to help them to introduce their own ranking system. I think this feature would add a lot of value to the site and produce a high level of user engagement.
