### ISSUE TITLE
[FEATURE] Claim without Decklists

### ISSUE THREAD

**Issue by lpoulter** [madarasz/always-be-running#31]
Many people have expressed dissatisfaction with the current enforcement of providing decklists with claims. The problem is partly because NRDB does not create a snapshot of private decklists but also because some people do not have the lists on NRDB or the event did not require decklists. 

A commonly requested feature is the ability to claim results without the need for decklists. Currently people are intentionally submitting incorrect lists or not claiming at all.

Some user comments:

- "I did claim my brighton spot with my bromley list (1 card off) because i couldnt be bothered"
- "Just to throw another voice in - I've played basically the same whizzard and CTM deck at 3-4 events on ABR, I don't want to have a 4 different lists for each with slightly different cards saved on NRDB"
- " frequently don't have decks saved on NRDB and so i've just added 'close enough' lists to some"

**Comment by madarasz** [comment]
The basic philosophy of ABR is: "no decklist = no glory". This might be a bit harsh, but this is the way I dreamt it. Please note that I also have KnowTheMeta which gets data from ABR.

I have a remedy for the private deck problem. I have a feature planned which publishes the user's private decklist upon claiming. This is not mandatory but will be turned on by default on the claiming form. This is supported by NetrunnerDB's API, so no problem there. 

Keep in mind that you can claim with the same decklist multiple times. You can also claim with someone else's published decklist. About the "almost/close enough" decklists, I'm not happy, but it's better than nothing.

I hope you all understand. I'm open to suggestions, ideas, let's keep the conversation going.

**Comment by lpoulter** [comment]
It's a tricky one, I agree that stats are great. However getting the number of users who engage with the site as high as possible seems like a good goal also. Allowing people to claim without a list would increase the number of claims but of course at the cost of number of decklists. 

I'm not sure if there is some half way option, the one you suggest is a good one and will help with part of them problem. However there will still be a subset of users that never claim because they don't want to share a list.

I not sure I agree that wrong decklists are better than nothing in some ways wrong data is worse than correct data.

**Comment by madarasz** [comment]
Done.
