### ISSUE TITLE
Sanity checking on n(players) and cut

### ISSUE THREAD

**Issue by tolaasin** [madarasz/always-be-running#35]
I've just tried to create a record for the finals of an online league, in which 4 players took part in double elimination. I set n(players)=4 and top cut of 4 - but this is rejected as 'the number of players in the cut must be less than the number of players.

I guess one option is to allow creation of simple double elimination events? Or I can kluge it by pretending there were 5 players.

Suggestions for this?

**Comment by madarasz** [comment]
Hey,
You have a couple of options:
- Create a tournament for your *entire* league with top4. Even if the places below 4th are not filled, it's fair to say that these 4 players bested the other 10+ players. 
- Create a tournament for 5 players with a dummy 5th player as you mentioned.

I support the tournament structure outlined by FFG rules. Anything custom is not likely to be supported. If it is requested by a lot of people then I might consider it. As for this tournament, I think these two options are perfectly fine.

**Comment by tolaasin** [comment]
Because it's league format, deck choices aren't appropriate for entry of anything below top 4, so I don't want to go down that route. It doesn't seem unreasonable to simply code for allowing equal to or less than in your sanity check. What's the harm in that? :)

**Comment by madarasz** [comment]
Have you already created this tournament? If so, which one is it?

I would like to push you toward the "option 1" that I have outlined. I understand that multiple decklists per person have been used throughout your league, so claiming below top-4 doesn't make sense. Then leave those places blank. It's better to see that your top-4 players have won overcoming twenty-something other participants. Also the winner will get a badge for winning a tournament with at least 8 players :)

If you are unsatisfied with this solution, then create a tournament with 5 players, top-4 and I will change it to 4 players total myself via the DB. Sorry if I sound to rigid and don't want to change the code, this problem sounds very niche and one-of. 

I hope this helps.

**Comment by tolaasin** [comment]
Your site, your call.  I don't think it's that niche, in that there are a few leagues going on which typically have double elimination finals. But sure, I can use option 1.

**Comment by madarasz** [comment]
Well, I find this option to better represent the league. In the future we might have multi-tournament leagues, claiming without decks (still deciding on that one). Which will help to represent the event we just talked about.

Wow, 40 players, nice 👍

**Comment by tolaasin** [comment]
45 players actually ... http://www.challengeboards.net/boards/standings/10387

**Comment by tolaasin** [comment]
wonder what I could do with that content ...
