### ISSUE TITLE
RSVP / check-in

### ISSUE THREAD

**Issue by carlsondc** [madarasz/always-be-running#36]
I recently conducted a survey of the Washington D.C. area players ( writeup[ here](https://docs.google.com/document/d/13AmGxWQlnitMU46kpnlM2T2xjVzd9kP6I1rMDuzHBuw/edit?usp=sharing), numbers [here](https://docs.google.com/forms/d/e/1FAIpQLSek04Gh7iXBnB_xfS7Y_5B-jTZYWwD0bKAj36gIHIkv9eOA4A/viewanalytics) ). 

One of the top reasons players gave for dictating their willingness to attend events was knowing they wouldn't show up and be the only player.

Having a simple check-in (with or without authentication) where people can easily indicate whether they plan to attend on a given week could be a nice way to centralize this and make it visible to players that are finding new meetups through the site.

Great work, by the way!

**Comment by madarasz** [comment]
Hey,

Thanks for reaching out to me.

There's already a "Register" / "Unregister" button on the tournaments for the same reason. (Anyway it's good to know it's not obvious.) Also my experience is that every tournament has a Facebook event which already has an RSVP function.

Thank you for providing me with your survey results, it's really valuable data.
