### ISSUE TITLE
Importing tournaments with missing identities

### ISSUE THREAD

**Issue by gereons** [madarasz/always-be-running#52]
I just wanted to conclude the Hamburg Regional https://alwaysberunning.net/tournaments/484/regional-atlantis using code 424199. This failed with the error message "Player Josh has no corp identity" (or something very close to this). Unfortunately the iPad that was used to run this tournament was a borrowed one and NRTM has already been deleted from it, along with all the data.

Is there a way to salvage this tournament?

**Comment by madarasz** [comment]
Fixed, two players were missing IDs.

**Comment by gereons** [comment]
There is indeed an inconsistency in NRTM's json file when exporting a tournament that has 1st round byes, so that may explain it.

**Comment by madarasz** [comment]
What kind of inconsistency? How should I handle it?

**Comment by gereons** [comment]
The inconsistency is that first-round byes to not show up in the pairings for the first round, where I think they should be, as games against player 0. Once I get around to fixing this  (hopefully later this week), I'll post an example file so you can check.

**Comment by gereons** [comment]
I finally got around to work on this. Attached is a test NRTM.json for 16 player dummy tournament:

- Round 1 started with Players 1, 2 and 3 having a first-round bye.
- Round 2 was played normally
- Round 3 started with a progression cut to the top 7 players
- Round 4 was player normally

I hope this testcase contains all possible weirdness that may occur with byes...


[NRTM.json.zip](https://github.com/madarasz/always-be-running/files/1133763/NRTM.json.zip)
