### ISSUE TITLE
Can't create location in tournament

### ISSUE THREAD

**Issue by 5N00P1** [madarasz/always-be-running#54]
Hi,

this tournament:
https://alwaysberunning.net/tournaments/752/1111-tournament-jakarta-ogre-kuningan-city

is listed as an online one. I've tried to fix it, but it won't let me save the location due to a missing city, which is obviously Jakarta

The correct string for google maps is:
Jl. Prof. DR. Satrio No.Kav. 18, RT.14/RW.4, Karet Kuningan, Kecamatan Setiabudi, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12940, Indonesien

**Comment by madarasz** [comment]
Sorry for taking my time, I was on vacation.

Huh, the wonders of Google Map :D It's quite hard to identify what the "city" is. Google Maps API returns me a bunch of address fragments and their function in a quite cryptic manner. So far I have figured out how things work, additionally there were small weird things in the US and UK. I'm guessing Indonesia has some weirdness going on as well.

Can we include the TO as well in the discussion? I have no knowledge what would qualify as the "city", "suburb", "neighbourhood", etc. in this certain place. 

So I'm getting the following address components:
- **Indonesia** - "country" - _this is fine_ 
- **Daerah Khusus Ibukota Jakarta** - "administrative_area_level_1" - _this is usually considered something as a "state" (in the US)_
- **Kota Jakarta Selatan** - "administrative_area_level_2"
- **Setia Budi** - "administrative_area_level_3" 
- **Karet Kuningan** - "administrative_area_level_4"

Usually there is an address component marked as "locality", "postal_town" or "sublocality_level_1" which should be the *city*.

So, which of the above would be the city?

**Comment by 5N00P1** [comment]
sure include / contact the TO, currently it shows up in all countries as it is an online tournament.
I have no contact with him so far.

**Comment by madarasz** [comment]
I have written him an email. Thx for spotting the problem.

**Comment by madarasz** [comment]
Fixed.
