### ISSUE TITLE
Admin Mode

### ISSUE THREAD

**Issue by 5N00P1** [madarasz/always-be-running#56]
For Admins it would be nice to act as a normal user most of the time and switch to admin mode only when they want to admin something. This is good standard in any kind of application and prevent errors.
For me I would feel more comfortable with it and hope it's not to hard to implement.

**Comment by madarasz** [comment]
Well, I would need to modify every code occurrence where the admin property of the user is checked. Or add another "real_admin" property to the user and use the previous "admin" property as the switch. But I do need to keep the admin property in case of name color or profile information...

So it's just complicated and I don't see the real value. What bothers you exactly? That you can see all the edit and delete buttons? Also this is only for a handful of people, not sure if the others need it as well.

I'm putting this on the list, but with low prio.

**Comment by 5N00P1** [comment]
I'm afraid I will delete a tournament sooner or later by accident or do some other crazy stuff. I can understand where this is coming from and we can keept it as it is.

**Comment by madarasz** [comment]
Good point, I just added a confirmation dialog on tournament delete, so you don't do that accidentally. Is there anything else that could be solved as such?

**Comment by 5N00P1** [comment]
This is great thank you!

From my point of view this applies to all the crazy stuff possible for an admin:
- remove a claim from some one
- remove fotos & videos

I think a confirmation might help but will also make it awkward.
To be honest, I would be perfectly happy with getting an admin account and being a normal user otherwise. The downside from my point of view, I don't get the requests for tournaments and thinks like that anymore...

**Comment by madarasz** [comment]
These are already there:

- confirmation to remove photo
- confirmation to remove video
- confirmation to remove video tag
- confirmation to remove someone else's claim
(there is no confirmation for removing an imported or your own claim)

**Comment by madarasz** [comment]
Closing this as I won't be implementing any admin/user switch.
