### ISSUE TITLE
Attaching video to in-progress tournament raises exception

### ISSUE THREAD

**Issue by carlsondc** [madarasz/always-be-running#58]
Attempted to add video to this event: https://alwaysberunning.net/tournaments/748/online-cache-refresh-2

The video in question was added using this url: https://www.youtube.com/watch?v=N0bCAH5yl78 

Here's a screencap of the error that I saw:

![image](https://user-images.githubusercontent.com/524641/29924969-d21ac2de-8e2c-11e7-918e-2311a52b6fe4.png)
![image](https://user-images.githubusercontent.com/524641/29924984-e0bb8c10-8e2c-11e7-993b-c9f75a2bbf0c.png)

**Comment by madarasz** [comment]
Hey,
Thx for posting the detailed bug-report, it helped a lot. The problem only happened when a video was zero seconds long after calculating hours and minutes (yours was 1 hour, 20 minutes and 0 seconds long). Should be fixed now.
