### ISSUE TITLE
Claiming for a tournament

### ISSUE THREAD

**Issue by 5N00P1** [madarasz/always-be-running#62]
There is a player that wanted to claim on ABR with his runner, but not with his corp as he got the list from some one else that did not allow him to share it. As a result he has created a fake Corp list to do so.
I would suggest to allow to claim with one list only, this is better, then the current situation.

See:
Malaysian Nationals, 2nd: https://alwaysberunning.net/tournaments/895/malaysia-anr-nationals-2017

The deck I'm reffering to is:
https://netrunnerdb.com/en/decklist/46388

**Comment by madarasz** [comment]
Uh-oh. Well, "claiming with one ID, with one decklist", I see that as a rare edge case. I do not want to make the claiming dialog even more complicated. For these rare situations, you can deal with it as the guy did, or just claim with IDs only.
