### ISSUE TITLE
Tagging videos

### ISSUE THREAD

**Issue by 5N00P1** [madarasz/always-be-running#63]
it would be nice, if the registered players would be sorted e.g. by name. In a tournament with >10 claims it's hard to find the players name. I assume the current sorting is starting with the first claim or something like that.

**Comment by madarasz** [comment]
Great idea!
I thought this is going to be an easy fix, unfortunately it's a bit more complicated. The fix I originally wrote screws up other functionality in some unexpected ways. First I need some autotests for the site and will get back to this later.

**Comment by madarasz** [comment]
Fixed.
