### ISSUE TITLE
[Feature request] syncronizing the event calendar with phone

### ISSUE THREAD

**Issue by bootcampdome** [madarasz/always-be-running#65]
A friend of mine and me are using a lot the phone calendar. 
It would be nice, if you can follow or include your calendar with the calendar on your mobile phone. 
To have a nice overview about tournaments and weekly meetups.

**Comment by madarasz** [comment]
Great idea! Let's clarify the details.

"Calendar" is a bit vague. What do you mean by that?
- **Single event**: You can add a tournament/recurring event to your personal calendar. This is from where we should start. There are existing solutions for this, like this ["add to calendar" button](https://www.addevent.com/add-to-calendar-button). 
- **All events in a country**: You might want to get all the events of a certain country. So do you download the *current snapshot* of all events? Then you won't get the new events in the future. I might publish the calendar of a country which you can *subscribe to*. I'm guessing we would need the latter, I have to look into that.
- **All events on ABR**: I think this is an overkill, but if "all events in a country" is working, this is easy.

Let's clarify how a single **calendar entry** of an ABR event would look like:
- **Start**: This is pretty obvious: "date"+"start time". "Start time" is not a mandatory field on ABR though. If "start time" is not given, I would make it an *all day event* in the calendar.
- **End**: ABR has no "end time field". Even as a tournament organiser it's hard to guess when a tournament ends, it also depends wether you make it into the top-cut. Some tournaments begin in the morning, some on the afternoon. As an universal solution, I would make it equal to "(end) date" + "23:59".
- **time zone**: This can be calculated from the location information. *Online events* complicate this a bit. I don't want to add another field for tournament creation on ABR just to clarify this. In case a tournament is *online*, it becomes an *all day event* in the calendar.
- **location**: Just copy from ABR.
- **description**: Just copy from ABR.
- **reminder alarm**: If the "start time" is given, then 2 hours before. If it's an *all day event* in the calendar, then 16:00 on the previous day.

**Comment by bootcampdome** [comment]
The Add to calendar button is great. 
What I mean is the following -  You can see, for what tournaments so signed up on ABR. On a calendar, there are also the recurring events. 
So what I want to have is: All the events, you signed up, are on your phone-calendar.

For example Facebook. You can have the events, where you participate also on your phone. 
It is like your sugguestion with the: "Add to calendar" button

to be honest: I am not a coder so my knowledge about coding and websites are pretty limited. 

All Events in a country seems pretty nice. Also all the tournaments, you signed up. That is what I would like to see on my calendar.

all the points of what clarifies a calendar entry of an ABR events are great. I like this very much.

**Comment by madarasz** [comment]
"Add to calendar" button added on the tournament detail pages (below QR code).

Some notes:
- Apple Calendar, Outlook works fine
- Google Calendar doesn't receive recurring and alarm options
- I did not test Outlook.com and online Yahoo calendars

Next step: ability to subscribe to a calendar of a country.
