### ISSUE TITLE
Cannot claim spot if user does not have a published decklist on one side

### ISSUE THREAD

**Issue by kevo31415** [madarasz/always-be-running#66]
I could not claim a finish in a tournament because I did not have a published runner decklist. I had a published corp decklist and intended to claim using another NRDB user's published decklist. Despite filling out the deck ID in the UI, the "no runner decklist" element threw an error. I had to publish a random runner deck I had laying around before I could claim my spot.

**Comment by madarasz** [comment]
Should be fixed now. Thx for raising the issue.
