### ISSUE TITLE
Suggestion: Improve the "Claims" dropdown menu

### ISSUE THREAD

**Issue by gereons** [madarasz/always-be-running#67]
... by adding the Player name and the current claims status in the dropdown. This could help reduce the number of conflicts. For example, for https://alwaysberunning.net/tournaments/913/hiveworld-store-championship this could look like this:

<img width="643" alt="bildschirmfoto 2018-03-04 um 19 35 38" src="https://user-images.githubusercontent.com/2861931/36949058-908e52b0-1fe3-11e8-851f-f5b2a66d9fcd.png">

**Comment by madarasz** [comment]
Great idea, will implement soon.

**Comment by madarasz** [comment]
Done

**Comment by gereons** [comment]
Minor issue I just noticed with this: the names are only added to the dropdown when you claim from the tournament's detail page. Clicking on "claim" in the results overview list shows just the numbers.
