### ISSUE TITLE
Missing player + duplicate player

### ISSUE THREAD

**Issue by gereons** [madarasz/always-be-running#69]
Hey Istvan, I've had a bug report from an NRTM user, and I've tried reproducing it using the JSON file from https://www.dropbox.com/sh/b6c0zv0bdttld0p/AADuJtUuWTwVViWiBrb55ohpa?dl=0 at tournament https://alwaysberunning.net/tournaments/1524/nrtm-test-tournament.

As you can see, Player 10, Sascha is listed twice, while Player 11, Aldo is missing completely, and I can't see anything wrong with the data. Could you take a look please?

**Comment by madarasz** [comment]
Thank you for the bugreport. Should be fixed now.
