### ISSUE TITLE
[Feature Request] Allow claiming with a mix of shared and published decks.

### ISSUE THREAD

**Issue by gereons** [madarasz/always-be-running#70]
Right now, both decks used when claiming must both be either shared private decks or published decks. This forced me to publish a duplicate of a published corp decks that I used just so I could claim with the (also now published) shared runner deck I used which was only a derivative of another deck.

**Comment by 5N00P1** [comment]
I think this has been fixed.

**Comment by madarasz** [comment]
@gereons could you check? I think you can claim with mixed decks.

**Comment by 5N00P1** [comment]
I have claimed this tournament with both, my own and another ones deck.
https://alwaysberunning.net/tournaments/2086/berlin-league-day-5

**Comment by gereons** [comment]
Indeed, this works now. Thanks!
