### ISSUE TITLE
Rename the "non-FFG tournament" tournament type.

### ISSUE THREAD

**Issue by gereons** [madarasz/always-be-running#75]
100% of all Netrunner tournaments are non-FFG tournaments nowadays, so the name really doesn't mean anything anymore :)

I suggest renaming it to "Community Tournament" because that's what it's used for mostly.

**Comment by madarasz** [comment]
I think I will rename it as "Non-NISEI" tournaments. Every event which is in the NISEI tournament structure and has NISEI prizes is a "NISEI" tournament. I will update the descriptions as well.

**Comment by madarasz** [comment]
Renamed to Community Tournament instead, thank you for the idea.
