### ISSUE TITLE
[Admin] Please add "Other" as a category for prize support when adding new kits as admin

### ISSUE THREAD

**Issue by vesperius** [madarasz/always-be-running#76]
![prize-kit-categories](https://user-images.githubusercontent.com/16701215/60730020-699cff80-9f44-11e9-8c37-c7e8c106db73.jpg)

The current selection is quite complete, but some of the prize kits do not fit into these categories and would fit better under "Other".

Thanks!

**Comment by madarasz** [comment]
Fixed.
